services:
  - type: web
    name: qat-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: qat-database
          property: connectionString
    autoDeploy: true

databases:
  - name: qat-database
    plan: free
    databaseName: qat_db
    user: qat_user
